apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: rnkbansal/devops-todo-app:latest # Make sure this is your username
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-app-config
        env:
        - name: SECRET_MESSAGE_FROM_K8S
          valueFrom:
            secretKeyRef:
              name: todo-app-secret
              key: SECRET_MESSAGE
        
        # --- ADD THE LIVENESS PROBE ---
        livenessProbe:
          httpGet:
            path: /healthz/live  # The URL path to check
            port: 3000          # The port inside the container
          initialDelaySeconds: 5  # Wait 5 seconds after the container starts before the first check
          periodSeconds: 10       # Check every 10 seconds

        # --- ADD THE READINESS PROBE ---
        readinessProbe:
          httpGet:
            path: /healthz/ready # The URL path to check
            port: 3000           # The port inside the container
          initialDelaySeconds: 5   # Wait 5 seconds before the first check
          periodSeconds: 10        # Check every 10 seconds
