apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: rnkbansal/devops-todo-app:latest # Make sure this is your username
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-app-config
        env: # <-- ADD THIS ENTIRE SECTION
        - name: SECRET_MESSAGE_FROM_K8S # The name of the environment variable inside the container
          valueFrom:
            secretKeyRef:
              name: todo-app-secret # The name of the Secret object we just created
              key: SECRET_MESSAGE # The key within that Secret whose value we want