apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        # my docker nameeeee
        image: rnkbansal/devops-todo-app:latest
        ports:
        - containerPort: 3000

        envForm:
        - configMapRef:
            name:todo-app-secret
        env:
        - name: SECRET_MESSAGE_FORM_KBS
        valueFrom:
          secretKeyRef:
          name: todo-app-secret
          key: SECRET_MESSAGE